import crypto from 'crypto';
import { query } from '../db';

const REFERRAL_CODE_PREFIX = 'HK';
const REFERRAL_CODE_ATTEMPTS = 20;

/**
 * Light profanity / lookalike-blocklist (Ch11-I078). We don't try to be
 * clever — these are the substrings that historically end up in user
 * complaints when they appear in autogenerated codes. Anything matching is
 * regenerated.
 */
const FORBIDDEN_SUBSTRINGS = ['FUCK', 'SHIT', 'CUNT', 'NIGGA', 'NIGGER', 'KILL', 'RAPE', 'NAZI'];

function isForbidden(code: string): boolean {
  const upper = code.toUpperCase();
  return FORBIDDEN_SUBSTRINGS.some((bad) => upper.includes(bad));
}

function formatReferralCode(raw: string): string {
  // 12 hex chars = 48 bits of entropy. The previous 8-hex format (32 bits)
  // hit collisions at ~4k codes; 48 bits is comfortable up to several
  // hundred million codes (Ch11-I076).
  const upper = raw.toUpperCase().slice(0, 12);
  return `${REFERRAL_CODE_PREFIX}-${upper.slice(0, 4)}-${upper.slice(4, 8)}-${upper.slice(8, 12)}`;
}

/**
 * Generate a referral code that does not collide with any existing user. The
 * caller MUST insert the code with a UNIQUE constraint in place; the SELECT
 * below is a hint only — race-safe code creation is the caller's job
 * (Ch11-I077). The atomic pattern is:
 *
 *   const code = await generateUniqueReferralCode();
 *   try {
 *     await query(`UPDATE users SET referral_code = $1 WHERE id = $2`, [code, id]);
 *   } catch (err) {
 *     if (err.code === '23505') retry;          // unique violation -> regenerate
 *   }
 */
export async function generateUniqueReferralCode(): Promise<string> {
  for (let attempt = 0; attempt < REFERRAL_CODE_ATTEMPTS; attempt += 1) {
    const raw = crypto.randomBytes(6).toString('hex');     // 48 bits
    const code = formatReferralCode(raw);
    if (isForbidden(code)) continue;

    // LOWER() comparison closes the audit's case-sensitive lookup hazard
    // (Ch11-I079). The lookup is advisory; the unique constraint on the
    // users table is the source of truth.
    const exists = await query(
      `SELECT 1 FROM users WHERE LOWER(referral_code) = LOWER($1) LIMIT 1`,
      [code],
    );
    if (exists.rows.length === 0) return code;
  }

  // Fallback: full UUID — same lookup rule but with much more entropy.
  const fullUuid = crypto.randomUUID().replace(/-/g, '').toUpperCase();
  const fallback = `${REFERRAL_CODE_PREFIX}-${fullUuid.slice(0, 4)}-${fullUuid.slice(4, 8)}-${fullUuid.slice(8, 12)}`;
  return fallback;
}
