name: havenkeep

packages:
  - apps/mobile
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  lint:
    run: melos exec -- dart analyze .
    description: Run static analysis on all packages.

  test:
    run: melos exec -- flutter test
    description: Run tests in all packages.
    packageFilters:
      dirExists: test

  format:
    run: melos exec -- dart format .
    description: Format all Dart code.

  clean:
    run: melos exec -- flutter clean
    description: Clean all packages.

  build:android:
    run: cd apps/mobile && flutter build apk
    description: Build Android APK.

  build:ios:
    run: cd apps/mobile && flutter build ios
    description: Build iOS app.
