#!/usr/bin/env bash
#
# regen-android-store-assets.sh — regenerate the Play Store listing
# assets (icon + feature graphic) from the brand source. Outputs land
# in apps/mobile/android/store-assets/ which is gitignored.
#
# Phone screenshots are NOT regenerated by this script — those are
# captured by running the app on a physical device or emulator and
# screenshotting the relevant screens manually.
#
# Usage (from repo root):
#   ./scripts/regen-android-store-assets.sh
#
# Reads:
#   apps/mobile/assets/icons/app-icon.png   (1024x1024 brand icon)
#
# Writes:
#   apps/mobile/android/store-assets/play-icon-512.png        (512x512)
#   apps/mobile/android/store-assets/play-feature-graphic.png (1024x500)
#
# Dependencies: macOS sips + Python 3 with Pillow.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="$REPO_ROOT/apps/mobile/android/store-assets"
ICON_SRC="$REPO_ROOT/apps/mobile/assets/icons/app-icon.png"

# Pick a Python with Pillow. Prefer a project-local venv if present;
# otherwise fall back to homebrew or system Python and require Pillow
# to be installed on it.
if [ -x "$REPO_ROOT/.venv/bin/python3" ]; then
  PYTHON="$REPO_ROOT/.venv/bin/python3"
elif command -v /opt/homebrew/bin/python3 >/dev/null; then
  PYTHON="/opt/homebrew/bin/python3"
else
  PYTHON="$(command -v python3)"
fi

mkdir -p "$OUT_DIR"

# 1. Icon: 1024 -> 512
sips -z 512 512 "$ICON_SRC" --out "$OUT_DIR/play-icon-512.png" > /dev/null

# 2. Feature graphic: dark navy background, indigo wordmark, emerald accent
"$PYTHON" - <<'PY'
from PIL import Image, ImageDraw, ImageFont
import os

repo_root = os.environ.get("REPO_ROOT") or os.path.expanduser("~/Projects/havenkeep")
out_dir = os.path.join(repo_root, "apps/mobile/android/store-assets")

W, H = 1024, 500
NAVY = (15, 23, 42)        # near-black navy
INDIGO = (99, 102, 241)    # #6366F1 — havenkeep primary
EMERALD = (16, 185, 129)   # #10B981 — havenkeep accent
INK_INVERT = (226, 232, 240)

img = Image.new("RGB", (W, H), NAVY)
draw = ImageDraw.Draw(img)

# Subtle indigo accent rules
draw.rectangle([80, H // 2 - 2, 200, H // 2], fill=INDIGO)
draw.rectangle([W - 200, H // 2 - 2, W - 80, H // 2], fill=INDIGO)

# Small emerald check accent above wordmark
cx, cy = W // 2, 100
draw.line([(cx - 18, cy), (cx - 6, cy + 14), (cx + 22, cy - 16)], fill=EMERALD, width=6)

wordmark = ImageFont.truetype("/System/Library/Fonts/Supplemental/Avenir Next.ttc", 110)
tagline = ImageFont.truetype("/System/Library/Fonts/Supplemental/Avenir Next.ttc", 38)

word = "HavenKeep"
bb = draw.textbbox((0, 0), word, font=wordmark)
draw.text(((W - (bb[2] - bb[0])) / 2, 175), word, font=wordmark, fill=INK_INVERT)

tag = "Your Warranties. Protected."
bb = draw.textbbox((0, 0), tag, font=tagline)
draw.text(((W - (bb[2] - bb[0])) / 2, 320), tag, font=tagline, fill=INDIGO)

img.save(os.path.join(out_dir, "play-feature-graphic.png"), "PNG", optimize=True)
PY

echo "Store assets regenerated in $OUT_DIR"
ls -la "$OUT_DIR"
